services:
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - spring-postgres
    depends_on:
      postgresdb:
       condition: service_healthy
  postgresdb:
    image: postgres:14.12
    restart: always
    user: postgres
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskmanagerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_pass
    networks:
      - spring-postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  volume:
networks:
  spring-postgres:
